### ISSUE TITLE
Rewrite VTEBench

### ISSUE THREAD

**Issue by chrisduerr** [alacritty/vtebench#20]
### Introduction

So there are a bunch of problems with vtebench which I'd like to see addressed.
The easiest solution to this is likely just to rewrite it from scratch, since it
is very simple at the moment.

To explain why I think a rewrite is necessary, I'd like to give an overview over
a few problems this application has that make development and use rather painful
at the moment.

### Writing Benchmarks

Currently it is quite painful to write benchmarks. There are a few very specific
and limited benchmarks which will inevitably lead to over-optimization for these
few special cases.

So writing benchmarks should be simple. In fact I shouldn't even need to know
anything about Rust to write them. We also do a lot of random input generation,
which isn't really beneficial to benchmarks. Randomness is only useful to test
multiple different things, for comparison it's much more useful when the input
is consistent every time vtebench is run.

As a solution I'd probably suggest a format that is just based on a plain text
file. Everyone extensively testing terminals should be capable of writing a few
escape sequences to a file. Then vtebench can just be used to repeat certain
parts of the file indefinitely. Some setup/teardown would probably be useful
that isn't repeated.

### Executing Benchmarks

Currently we have a script to at least generate semi useful benchmarks. But
looking at that script will probably fill you with horror. Running the program
itself, timing it, then redirecting it to a file is extremely inconsistent. Not
only will the benchmark's duration be different since we now cat directly from a
file, but this also completely breaks any reasonable cleanup.

Having some internal timers to generate benchmarks would likely be useful. Being
able to just tell the application you want to run for about X seconds and then
having it spit out how many bytes it was able to write is likely very useful in
general. Though I'd imagine being able to time it externally might still be
useful, even if vtebench is capable of doing everything on its own.

### Performance

To be able to achieve the goals of easier benchmark execution, it's important
that the performance is checked again. Currently vtebench was written with the
goal of just being run directly, but then we need to redirect it to actually
benchmark some terminals since it is not fast enough.

Ideally the performance should be good enough that at least internal timing is
capable of measuring the exact time it would take to cat the output file. This
could be done by filling an internal buffer before starting a timer. Memory
usage should not be a problem at all with vtebench.

### Summary

So here are my suggestions for a rewrite:
 - Text files as benchmarks
 - Add internal timing support
 - Improve output performance to match `cat` speed

**Comment by kchibisov** [comment]
>Currently it is quite painful to write benchmarks. There are a few very specific
and limited benchmarks which will inevitably lead to over-optimization for these
few special cases.

>So writing benchmarks should be simple. In fact I shouldn't even need to know
anything about Rust to write them. We also do a lot of random input generation,
which isn't really beneficial to benchmarks. Randomness is only useful to test
multiple different things, for comparison it's much more useful when the input
is consistent every time vtebench is run.

>As a solution I'd probably suggest a format that is just based on a plain text
file. Everyone extensively testing terminals should be capable of writing a few
escape sequences to a file. Then vtebench can just be used to repeat certain
parts of the file indefinitely. Some setup/teardown would probably be useful
that isn't repeated.

The question is what part vtebench will be automating here? You know, that you can write shell scripts to generate things without much issue. Also it should provide some builtin benchmarks, since users who are writing patches, that are touching perf couldn't be fluent with escape sequences.

If you want to have some dsl to write benchmarks relatively easy for terminals, maybe you can brought that issue to terminal-wg and ask them if they're interested in developing something like that for easy of testing of terminal performance?

>Currently we have a script to at least generate semi useful benchmarks. But
looking at that script will probably fill you with horror. Running the program
itself, timing it, then redirecting it to a file is extremely inconsistent. Not
only will the benchmark's duration be different since we now cat directly from a
file, but this also completely breaks any reasonable cleanup.

>Having some internal timers to generate benchmarks would likely be useful. Being
able to just tell the application you want to run for about X seconds and then
having it spit out how many bytes it was able to write is likely very useful in
general. Though I'd imagine being able to time it externally might still be
useful, even if vtebench is capable of doing everything on its own.

I personally don't really like time based approach in the script and I also don't like that script in particular. I usually benchmark on specific sizes of the output, so it gives a good reflection on how machine X compared to machine Y, since they have the same size of the window, just different hardware).

>To be able to achieve the goals of easier benchmark execution, it's important
that the performance is checked again. Currently vtebench was written with the
goal of just being run directly, but then we need to redirect it to actually
benchmark some terminals since it is not fast enough.

>Ideally the performance should be good enough that at least internal timing is
capable of measuring the exact time it would take to cat the output file. This
could be done by filling an internal buffer before starting a timer. Memory
usage should not be a problem at all with vtebench.

I do like cat approach more since it's less noise, however the current problem with vtebench is not noise from running directly, but that it generates random things, while with cat you don't have any random at all. I'm still using the same file from vtebench I've generated like months ago. So I'd rather focus on ability to generate different benchmarks, rather than running directly and being compatible with `cat`, since outsourcing job to tools that are good at one thing is better than having a 'generator + parser + execution` in one tool, where execution part could be entirely done by existing tools `perf + cat` and it'll work much better, since you completely skip generating part each time your run `vtebench`.

That's just some thoughts of someone who is dealing with vtebench from time to time.

**Comment by chrisduerr** [comment]
> The question is what part vtebench will be automating here? You know, that you can write shell scripts to generate things without much issue.

That's a good point. I suppose the main benefit would be that vtebench can wrap around these benchmarks and control them. So it could easily buffer some output and write to stdout for X seconds and then stop, without having to kill processes or something.

That said, I'm not suggesting that people would always re-write these benchmarks. Even if benchmarks are text files or scripts, I'd still store them in this repo. In general I don't see a necessity to use Rust here if we can provide a better solution without it.

> I personally don't really like time based approach in the script and I also don't like that script in particular. I usually benchmark on specific sizes of the output, so it gives a good reflection on how machine X compared to machine Y, since they have the same size of the window, just different hardware).

I think the main advantage of time is for generation. I don't expect anyone to be able to select a good size when first generating a benchmark, there's simply no way to tell. However most people would be able to intuitively figure out that a benchmark should run for a couple of seconds.

So the time would just be useful to generate the benchmark, the actual size could of course also be printed to stdout in case you want to repeat it.

> I do like cat approach more since it's less noise, however the current problem with vtebench is not noise from running directly, but that it generates random things

I mean that's not a problem right now. You should redirect it to a file anyways. With a constant byte size the ability to not actually run into any terminal bottlenecks is a much bigger problem than consistency between generated output. Though both are not ideal.

> since outsourcing job to tools that are good at one thing is better than having a generator + parser + executionin one tool

That's the thing though, `cat` is good at writing a file to stdout but that's not necessary at all. There's no reason why we would need File I/O as a potential bottleneck, when we could basically just run it from RAM. The tool is good for one thing, but the one thing it's good at is not really what we want ourselves.

**Comment by kchibisov** [comment]
>In general I don't see a necessity to use Rust here if we can provide a better solution without it.

Well, one minor benefit in using rust here is that shell scripts(or C) on windows are not that easy to bootstrap, so it could leave us with e.g. python, which I'm not really opposed to use.

>That's the thing though, cat is good at writing a file to stdout but that's not necessary at all. There's no reason why we would need File I/O as a potential bottleneck, when we could basically just run it from RAM. The tool is good for one thing, but the one thing it's good at is not really what we want ourselves.

It must go to ram if you run it a bunch of times, I don't see any reason to measure cold runs, and I've never measured cold runs myself, so `cat` is still good?

**Comment by chrisduerr** [comment]
> Well, one minor benefit in using rust here is that shell scripts(or C) on windows are not that easy to bootstrap, so it could leave us with e.g. python, which I'm not really opposed to use.

I've been thinking about that and it might be useful to have not a script but just raw escape sequences in a file. That way we could even load things at compile time. No need for anything like a script to generate the benchmarks every time. All we need is a single payload, say a fixed size of useful data, that can then be repeated and cached in memory.

> It must go to ram if you run it a bunch of times, I don't see any reason to measure cold runs, and I've never measured cold runs myself, so cat is still good?

But there's very little control over that and it's easy to mess up. Ideally `cargo run --release` should be all that is required to get some basic numbers. Of course we can still make it possible to just generate raw benchmark files that can be tested with `cat`, but I don't think we should rely on the operating system caching things for us until we can determine that our benchmarks are useful at all.

**Comment by kchibisov** [comment]
>But there's very little control over that and it's easy to mess up. Ideally cargo run --release should be all that is required to get some basic numbers. Of course we can still make it possible to just generate raw benchmark files that can be tested with cat, but I don't think we should rely on the operating system caching things for us until we can determine that our benchmarks are useful at all.

Oh, so you want to measure things in `vtebench`? In general I don't see an issues with that and it could be more useful than doing `cat` + `perf`, since you just run things out of memory and thing like aslr don't matter.
